name: obf2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - anyio=3.3.0=py39hcbf5309_0
  - argon2-cffi=20.1.0=py39hb82d6ee_2
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd8ed1ab_0
  - bottleneck=1.3.2=py39h7cc1a96_1
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py39hb82d6ee_1001
  - ca-certificates=2021.5.30=h5b45459_0
  - certifi=2021.5.30=py39hcbf5309_0
  - cffi=1.14.6=py39h0878f49_1
  - chardet=4.0.0=py39hcbf5309_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.7=py39hd8d06c1_0
  - cudatoolkit=10.2.89=h74a9793_1
  - cycler=0.10.0=py39haa95532_0
  - debugpy=1.4.1=py39h415ef7b_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=4.8.1=py39hcbf5309_0
  - intel-openmp=2021.3.0=haa95532_3372
  - ipykernel=6.4.1=py39h832f523_0
  - ipython=7.27.0=py39h832f523_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py39hcbf5309_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=hb83a4c4_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=7.0.3=pyhd8ed1ab_0
  - jupyter_core=4.8.1=py39hcbf5309_0
  - jupyter_server=1.11.0=pyhd8ed1ab_0
  - jupyterlab=3.1.12=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.8.1=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py39hd77b12b_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.17.2=h23ce68f_1
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.40.0=he774522_0
  - lz4-c=1.9.3=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.0.1=py39hb82d6ee_0
  - matplotlib=3.4.2=py39haa95532_0
  - matplotlib-base=3.4.2=py39h49ac443_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py39hb82d6ee_1004
  - mkl=2021.3.0=haa95532_524
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.0=py39h277e83a_2
  - mkl_random=1.2.2=py39hf11a4ad_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=py_0
  - nbclassic=0.3.2=pyhd8ed1ab_0
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbconvert=6.1.0=py39hcbf5309_1
  - nbformat=5.1.3=pyhd8ed1ab_0
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - ninja=1.10.2=h6d14046_1
  - notebook=6.4.4=pyha770c72_0
  - numexpr=2.7.3=py39hb80d3ca_1
  - numpy=1.20.3=py39ha4e8547_0
  - numpy-base=1.20.3=py39hc2deb75_0
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1l=h8ffe710_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.2=py39h6214cd6_0
  - pandoc=2.14.2=h8ffe710_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.1=py39h4fa10fc_0
  - pip=21.2.4=py38haa95532_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - protobuf=3.17.2=py39hd77b12b_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py39hd77b12b_6
  - pyrsistent=0.17.3=py39hb82d6ee_2
  - pysocks=1.7.1=py39hcbf5309_3
  - python=3.9.7=h6244533_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.9.0=py3.9_cuda10.2_cudnn7_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pywin32=301=py39hb82d6ee_0
  - pywinpty=0.5.7=py39hcbf5309_1
  - pyzmq=22.3.0=py39he46f08e_0
  - qt=5.9.7=vc14h73c81de_0
  - requests=2.25.1=pyhd3deb0d_0
  - requests-unixsocket=0.2.0=py_0
  - scikit-learn=0.24.2=py39hf11a4ad_1
  - scipy=1.7.1=py39hbe87c03_2
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.0.4=py39haa95532_0
  - sip=4.19.13=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_0
  - sniffio=1.2.0=py39hcbf5309_1
  - sqlite=3.36.0=h2bbff1b_0
  - tensorboardx=2.2=pyhd3eb1b0_0
  - termcolor=1.1.0=py39haa95532_1
  - terminado=0.9.4=py39hcbf5309_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.10=he774522_0
  - torchaudio=0.9.0=py39
  - torchvision=0.10.0=py39_cu102
  - tornado=6.1=py39h2bbff1b_0
  - tqdm=4.62.2=pyhd3eb1b0_1
  - traitlets=5.1.0=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021a=h5d7bf9c_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=0.57.0=py39hcbf5309_4
  - wheel=0.37.0=pyhd3eb1b0_1
  - win_inet_pton=1.1.0=py39hcbf5309_2
  - wincertstore=0.2=py39h2bbff1b_0
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
prefix: C:\Users\beibi\.conda\envs\obf2
